## Seminar Paper on Causal Inference - Empirics

## Data Loading and Initial Preparation

In [ ]:
import os
import pandas as pd
import numpy as np
from scipy import stats
import statsmodels.api as sm
import warnings
warnings.filterwarnings('ignore')

df = pd.read_stata("./data/Cleandata.dta")


data = df.copy()
data.head()

,stdntid,gender,race,birthmonth,birthday,birthyear,flagsgk,flagsg1,flagsg2,flagsg3,flaggk,flagg1,flagg2,flagg3,flagg4,flagg5,flagg6,flagg7,flagg8,flagprt4,flagidn8,flagprt8,flagsatact,flaghscourse,flaghsgraduate,g0classtype,g1classtype,g2classtype,g3classtype,cmpstype,cmpsdura,yearsstar,yearssmall,g0schid,gksurban,g0tchid,g0tgen,g0trace,g0thighdegree,gktcareer,g0tyears,g0classsize,g0freelunch,gkrepeat,gkspeced,gkspecin,gkpresent,gkabsent,g0treadss,g0tmathss,gktlistss,g0wordskillss,gkmotivraw,gkselfconcraw,g1schid,g1surban,g1tchid,g1tgen,g1trace,g1thighdegree,g1tcareer,g1tyears,g1classsize,g1freelunch,g1promote,g1speced,g1specin,g1present,g1absent,g1treadss,g1tmathss,g1tlistss,g1wordskillss,g1readbsraw,g1mathbsraw,g1readbsobjraw,g1mathbsobjraw,g1readbsobjpct,g1mathbsobjpct,g1motivraw,g1selfconcraw,g2schid,g2surban,g2tchid,g2tgen,g2trace,g2thighdegree,g2tcareer,g2tyears,g2ttrain,g2classsize,g2freelunch,g2promote,g2treadss,g2tmathss,g2tlistss,g2wordskillss,g2readbsraw,g2mathbsraw,g2readbsobjraw,g2mathbsobjraw,g2readbsobjpct,g2mathbsobjpct,g2motivraw,g2selfconcraw,g3schid,g3surban,g3tchid,g3tgen,g3trace,g3thighdegree,g3tcareer,g3tyears,g3ttrain,g3classsize,g3freelunch,g3promote,g3present,g3absent,g3treadss,g3tmathss,g3tlangss,g3tlistss,g3sciencess,g3socialsciss,g3spellss,g3vocabss,g3mathcomputss,g3mathnumconcss,g3mathapplss,g3wordskillss,g3readbsraw,g3mathbsraw,g3readbsobjraw,g3mathbsobjraw,g3readbsobjpct,g3mathbsobjpct,g3motivraw,g3selfconcraw,g4schid,g4surban,g4tchid,g4tgen,g4trace,g4nclass,g4nwhite,g4nblack,g4nother,g4pernwh,g4nfreelunch,g4treadss,g4tmathss,g4tlangss,g4tbattss,g4sciencess,g4socialsciss,g4readcomprehss,g4spellss,g4vocabss,g4mathcomputss,g4mathconcapplss,g4langexpss,g4langmechss,g4studyskillss,g4readbsobjraw,g4mathbsobjraw,g4ptattn,g4pthwrk,g4ptothr,g4ptmtrl,g4ptlate,g4ptries,g4ptrstl,g4ptdisc,g4ptwork,g4ptimpt,g4ptrepr,g4ptanoy,g4ptpers,g4ptknow,g4ptextr,g4ptwthd,g4ptefrt,g4ptcrit,g4ptasks,g4ptalks,g4ptintv,g4pteasy,g4ptcrts,g4ptfnsh,g4ptrais,g4ptseek,g4ptdsrg,g4ptdiss,g4ptextc,g4ptperf,g4ptsped,g4pteffr,g4ptinit,g4ptnonp,g4ptvalu,g5schid,g5treadss,g5tmathss,g5tlangss,g5tbattss,g5sciencess,g5socialsciss,g5readcomprehss,g5spellss,g5vocabss,g5mathcomputss,g5mathconcapplss,g5langexpss,g5langmechss,g5studyskillss,g5readbsobjraw,g5mathbsobjraw,g6schid,g6treadss,g6tmathss,g6tlangss,g6sciencess,g6socialsciss,g6readbsobjraw,g6mathbsobjraw,g7schid,g7treadss,g7tmathss,g7tlangss,g7tbattss,g7sciencess,g7socialsciss,g7readcomprehss,g7spellss,g7vocabss,g7mathcomputss,g7mathconcapplss,g7langexpss,g7langmechss,g7studyskillss,g7readbsobjraw,g7mathbsobjraw,g8schid,g8surban,g8treadss,g8tmathss,g8tlangss,g8tbatts,g8sciencess,g8socialsciss,g8readco,g8spells,g8vocabs,g8mathco,g8math_a,g8langex,g8langme,g8studys,g8readbsobjraw,g8mathbsobjraw,g8idprou,g8idrspt,g8idgdjb,g8idattn,g8idactv,g8idimpt,g8idpopu,g8idusls,g8idfrnl,g8idcare,g8idplac,g8idprob,g8idusef,g8idfrnc,g8idtryg,g8idfavr,g8idintr,g8idwast,g8iddrop,g8idfrnu,g8idmimp,g8idfrnw,g8idfrns,g8idblng,g8idvalu,g8idtotl,g8peabsn,g8peprnt,g8peattn,g8pemtrl,g8peasgn,g8pelate,g8pepers,g8pecrts,g8pemore,g8peanoy,g8pevalu,g8pecrit,g8pedisc,g8perepr,g8peabus,g8pediss,g8peeffr,g8peinit,g8penonp,g8pmabsn,g8pmprnt,g8pmattn,g8pmmtrl,g8pmasgn,g8pmlate,g8pmpers,g8pmcrts,g8pmmore,g8pmanoy,g8pmvalu,g8pmcrit,g8pmdisc,g8pmrepr,g8pmabus,g8pmdiss,g8pmeffr,g8pminit,g8pmnonp,hsid,hsfrnch1,hsfrnch2,hsfrnch3,hsfrnch4,hsgrmn1,hsgrmn2,hsgrmn3,hsgrmn4,hslatin1sem,hslatin2sem,hslatin3sem,hslatin4sem,hsspani1,hsspani2,hsspani3,hsspani4,hsspani5,hsflang1sem,hsflang2sem,hsflang3sem,hsflang4sem,hsflangtotsem,hsmath1,hsmath2,hsmath3,hsmath4,hsmath5,hsmathtotsem,hsciento,hsgpaflang,hsgpamath,hsgpascience,hsgpaoverall,hslvlfla,hslvlmth,hsyrscor,hsctsrc,hssat,hsact,hstest,hssatmath,hssatverbal,hssattot,hsactcomp,hsacttot,hsactenglish,hsactmath,hsactread,hsactscience,hssatconverted,hsactconverted,hsgrdadd,hsgrdcol,gradeenter,WhiteAsian,bday,startschool,age,g0freelunch_2,g1freelunch_2,g2freelunch_2,g3freelunch_2,girl,g0attrition,g1attrition,g2attrition,g3attrition,g0treadxt,g0tmathxt,g0wordskillxt,g0SAT,g1treadxt,g1tmathxt,g1wordskillxt,g1SAT,g2treadxt,g2tmathxt,g2wordskillxt,g2SAT,g3treadxt,g3tmathxt,g3wordskillxt,g3SAT,g0twhite,g1twhite,g2twhite,g3twhite,g0md,g1md,g2md,g3md,WhiteTeacher0,WhiteTeacher1,WhiteTeacher2,WhiteTeacher3,MaleTeacher0,MaleTeacher1,MaleTeacher2,MaleTeacher3,g0s,g0r,g0ra,g1s,g1r,g1ra,g2s,g2r,g2ra,g3s,g3r,g3ra,fyclasstype,initials,initialr,initialra
0,11465,male,black,march,13.0,1979.0,no,no,no,yes,no,no,no,yes,yes,no,no,no,no,no,no,no,no,no,no,NaN,NaN,NaN,REGULAR CLASS,regular,1.0,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,169280.0,suburban,16928012.0,female,white,bachelors,LADDER LEVEL 1,30.0,"NO, DID NOT ATTEND STAR TRAINING",25.0,FREE LUNCH,"YES, PROMOTION RECOMMENDED",123.0,37.0,499.0,510.0,536.0,NaN,NaN,543.0,547.0,NaN,478.0,542.0,499.0,477.0,NaN,NaN,NaN,NaN,NaN,NaN,48.0,40.0,169280.0,suburban,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,499.0,572.0,576.0,585.0,564.0,560.0,619.0,611.0,593.0,542.0,601.0,603.0,549.0,539.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,no,no,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,0.0,7011.0,9375.0,6.476712,NaN,NaN,NaN,1.0,0.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000490,0.000483,0.000233,0.040208,NaN,NaN,NaN,1.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,0.0,2.0,0.0,1.0,0.0
1,11047,male,black,august,30.0,1978.0,no,no,no,yes,no,no,no,yes,yes,yes,no,no,no,no,no,no,no,no,no,NaN,NaN,NaN,REGULAR + AIDE CLASS,aide,1.0,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,193422.0,rural,19342213.0,female,white,masters,LADDER LEVEL 2,17.0,"NO, DID NOT ATTEND STAR TRAINING",25.0,FREE LUNCH,"YES, PROMOTION RECOMMENDED",145.0,15.0,499.0,536.0,559.0,564.0,577.0,567.0,557.0,556.0,545.0,526.0,535.0,483.0,16.0,26.0,2.0,4.0,20.0,27.0,34.0,39.0,193422.0,rural,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,499.0,626.0,661.0,617.0,564.0,560.0,605.0,496.0,526.0,645.0,607.0,646.0,675.0,516.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,193422.0,562.0,596.0,592.0,583.0,586.0,673.0,553.0,536.0,571.0,598.0,593.0,610.0,574.0,558.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,no,no,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,0.0,6816.0,9375.0,7.010959,NaN,NaN,NaN,1.0,0.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000245,0.013288,0.000467,0.466663,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,3.0,0.0,0.0,1.0
2,20757,male,white,october,22.0,1979.0,no,no,no,yes,no,no,no,yes,yes,no,yes,no,yes,no,yes,yes,no,no,no,NaN,NaN,NaN,REGULAR + AIDE CLASS,aide,1.0,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,264945.0,suburban,26494517.0,female,white,masters,LADDER LEVEL 1,16.0,"NO, DID NOT ATTEND STAR TRAINING",28.0,NON-FREE LUNCH,"YES, PROMOTION RECOMMENDED",64.0,7.0,525.0,531.0,554.0,588.0,553.0,538.0,557.0,580.0,516.0,532.0,545.0,494.0,8.0,22.0,0.0,3.0,0.0,20.0,48.0,36.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,525.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,264953.0,670.0,707.0,668.0,595.0,601.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,264952.0,suburban,650.0,741.0,702.0,698.0,627.0,716.0,705.0,703.0,595.0,740.0,742.0,715.0,689.0,735.0,1.0,0.0,agree,STRONGLY AGREE,disagree,STRONGLY AGREE,disagree,STRONGLY DISAGREE,STRONGLY DISAGREE,disagree,STRONGLY DISAGREE,STRONGLY DISAGREE,STRONGLY AGREE,STRONGLY AGREE,agree,STRONGLY AGREE,STRONGLY AGREE,STRONGLY DISAGREE,disagree,STRONGLY AGREE,disagree,agree,STRONGLY AGREE,agree,disagree,26.0,21.0,47.0,1-2 ABSENCES,NO CONTACTS,always,4.0,4.0,never,sometimes,never,never,never,always,never,4.0,2.0,never,2.0,19.0,7.0,4.0,1-2 ABSENCES,NO CONTACTS,always,4.0,4.0,never,sometimes,never,never,never,always,never,4.0,2.0,never,2.0,19.0,7.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,no,no,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0,7234.0,9375.0,5.865754,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.004651,0.005315,0.000700,0.355558,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,3.0,0.0,0.0,1.0
3,12959,male,black,july,25.0,1979.0,no,yes,yes,yes,no,yes,yes,yes,yes,no,no,no,no,no,no,no,no,no,yes,NaN,REGULAR CLASS,REGULAR CLASS,REGULAR CLASS,regular,3.0,3,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,244780.0,INNER CITY,24478004.0,female,white,bachelors,apprentice,2.0,25.0,FREE LUNCH,"YES, PROMOTION RECOMMENDED",no,no,160.0,0.0,444.0,488.0,548.0,421.0,13.0,43.0,2.0,11.0,25.0,100.0,50.0,50.0,244780.0,INNER CITY,24478008.0,female,white,bachelors,apprentice,1.0,"NO, DID NOT ATTEND STAR TRAINING",21.0,FREE LUNCH,"YES, PROMOTION RECOMMENDED",503.0,530.0,599.0,500.0,19.0,44.0,2.0,10.0,73.0,67.0,51.0,53.0,244780.0,INNER CITY,24478010.0,female,white,bachelors,CHOSE NO TO BE ON CAREER LADDER,3.0,"NO, DID NOT ATTEND STAR TRAINING",24.0,FREE LUNCH,"YES, PROMOTION RECOMMENDED",157.0,3.0,513.0,533.0,539.0,551.0,528.0,555.0,541.0,526.0,532.0,547.0,519.0,494.0,9.0,33.0,1.0,6.0,10.0,40.0,53.0,42.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,513.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,244837.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,no,no,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DROPPED OUT,no,1.0,0.0,7145.0,9375.0,6.109589,NaN,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.064086,0.179666,0.037872,9.38745,0.035723,0.135173,0.050101,7.366544,0.001224,0.008456,0.000934,0.353795,NaN,1.0,1.0,1.0,NaN,0.0,0.0,0.0,NaN,1.0,1.0,1.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,2.0,0.0,1.0,0.0
4,19191,female,black,arpil,28.0,1979.0,no,no,yes,yes,no,no,yes,yes,no,no,no,no,no,no,no,no,no,no,yes,NaN,NaN,REGULAR + AIDE CLASS,REGULAR + AIDE CLASS,aide,2.0,2,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,244728.0,INNER CITY,24472809.0,female,white,masters,LADDER LEVEL 1,13.0,"NO, DID NOT ATTEND STAR TRAINING",22.0,FREE LUNCH,"YES, PROMOTION RECOMMENDED",494.0,486.0,529.0,510.0,13.0,20.0,1.0,2.0,33.0,13.0,NaN,NaN,244728.0,INNER CITY,24472812.0,female,black,masters,LADDER LEVEL 2,13.0,"NO, DID NOT ATTEND STAR TRAINING",26.0,FREE LUNCH,"YES, PROMOTION RECOMMENDED",148.0,12.0,NaN,NaN,NaN,NaN,523.0,567.0,517.0,539.0,521.0,514.0,513.0,499.0,NaN,NaN,2.0,0.0,NaN,NaN,49.0,43.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,244721.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,no,no,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,graduated,yes,2.0,0.0,7057.0,9375.0,6.350685,NaN,NaN,1.0,1.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.016110,0.010992,0.087676,3.825931,NaN,NaN,0.001167,0.116713,NaN,NaN,1.0,0.0,NaN,NaN,1.0,1.0,NaN,NaN,1.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,1.0,3.0,0.0,0.0,1.0

In [77]:
# Create initial assignment groups from fyclasstype
df['initial_small'] = (df['fyclasstype'] == 1).astype(int)
df['initial_regular'] = (df['fyclasstype'] == 2).astype(int)
df['initial_ra'] = (df['fyclasstype'] == 3).astype(int)

print(f"Initial assignment distribution:")
print(f"  Small: {df['initial_small'].sum()} ({df['initial_small'].mean()*100:.1f}%)")
print(f"  Regular: {df['initial_regular'].sum()} ({df['initial_regular'].mean()*100:.1f}%)")
print(f"  Regular/Aide: {df['initial_ra'].sum()} ({df['initial_ra'].mean()*100:.1f}%)")

Initial assignment distribution:
  Small: 3024 (26.1%)
  Regular: 4328 (37.3%)
  Regular/Aide: 4249 (36.6%)

In [78]:
# ==========================================
# Prepare Demographic Variables
# ==========================================

# 1. Gender: Create a binary 'girl' indicator (1 = female, 0 = male/missing)
df['girl'] = df['gender'].str.lower().map({'male': 0, 'female': 1}).fillna(0).astype(int)

# 2. Race/Ethnicity: Ensure binary format for White/Asian indicator
df['white_asian'] = df['WhiteAsian'].fillna(0).astype(int)

# 3. Age: Calculate age as of September 1, 1985
# Convert day and year to numeric, coercing any errors to NaN
df['birth_day'] = pd.to_numeric(df['birthday'], errors='coerce')
df['birth_year'] = pd.to_numeric(df['birthyear'], errors='coerce')

# Map string months to numeric values
month_map = {
    'january': 1, 'february': 2, 'march': 3, 'april': 4,
    'may': 5, 'june': 6, 'july': 7, 'august': 8,
    'september': 9, 'october': 10, 'november': 11, 'december': 12
}

# Use a temporary series for the numeric month to avoid cluttering the DataFrame
birth_month_num = df['birthmonth'].str.lower().map(month_map)

# Calculate base age based purely on the birth year
df['age_1985'] = 1985 - df['birth_year']

# Adjust age for students born strictly after September 1st 
# (i.e., they haven't had their 1985 birthday yet by Sept 1)
born_after_sept_1st = (birth_month_num > 9) | ((birth_month_num == 9) & (df['birth_day'] > 1))
df.loc[born_after_sept_1st, 'age_1985'] -= 1

# Note: age_1985 will be a float due to NaN values (from errors='coerce'). 
# If you need it as an integer and are sure there are no NaNs, you can uncomment the line below:
# df['age_1985'] = df['age_1985'].astype(int)

## Data Cleaning and Variable Preparation

In [79]:
df[['birthmonth', 'birthyear', 'age_1985']].head()

  birthmonth  birthyear  age_1985
0      march     1979.0       6.0
1     august     1978.0       7.0
2    october     1979.0       5.0
3       july     1979.0       6.0
4      arpil     1979.0       6.0

In [80]:
df['age_1985'].unique()

array([ 6.,  7.,  5.,  4.,  8.,  3., nan])

In [81]:
# Prepare free lunch variables
for grade in ['0', '1', '2', '3']:
    col = f'g{grade}freelunch_2'
    if col in df.columns:
        df[f'free_lunch_{grade}'] = df[col].fillna(0).astype(int)

In [82]:
# Convert test scores to percentiles as described in the article
# First, ensure test scores are numeric
for grade in ['0', '1', '2', '3']:
    for subject in ['treadss', 'tmathss', 'wordskillss']:
        col = f'g{grade}{subject}'
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors='coerce')

# Convert class type columns to numeric categories
for grade in ['0', '1', '2', '3']:
    col = f'g{grade}classtype'
    if col in df.columns:
        # Map string values to numeric codes
        df[col] = df[col].astype(str)
        class_mapping = {
            'SMALL CLASS': 1,
            'REGULAR CLASS': 2, 
            'REGULAR + AIDE CLASS': 3,
            'REGULAR+AIDE CLASS': 3,
            'SMALL': 1,
            'REGULAR': 2,
            'REGULAR+AIDE': 3
        }
        df[col] = df[col].map(class_mapping)

In [83]:
def calculate_percentile_score(row, grade, control_group_scores):
    """Calculate percentile rank relative to control group."""
    score = row
    if pd.isna(score):
        return np.nan
    # Percentile = (number of scores below this score / total scores) * 100
    return (np.sum(control_group_scores < score) / len(control_group_scores)) * 100

In [84]:
# Calculate percentiles for each grade
for grade in ['0', '1', '2', '3']:
    # Get the average of three SAT tests
    test_cols = [f'g{grade}treadss', f'g{grade}tmathss', f'g{grade}wordskillss']
    if all(col in df.columns for col in test_cols):
        df[f'sat_avg_{grade}'] = df[test_cols].mean(axis=1)
        
        # Get control group (regular and regular/aide) for this grade
        class_col = f'g{grade}classtype'
        if class_col in df.columns:
            # Control group = regular (2) and regular/aide (3)
            control_mask = df[class_col].isin([2, 3])
            control_scores = df.loc[control_mask, f'sat_avg_{grade}'].dropna()
            
            if len(control_scores) > 0:
                # Calculate percentile for each student
                df[f'percentile_{grade}'] = df[f'sat_avg_{grade}'].apply(
                    lambda x: calculate_percentile_score(x, grade, control_scores)
                )
                
                # Verify: control group should have mean percentile around 50
                control_percentiles = df.loc[control_mask, f'percentile_{grade}'].mean()
                print(f"  Grade {grade}: Control group N={len(control_scores)}, Mean percentile={control_percentiles:.1f}")

  Grade 0: Control group N=4130, Mean percentile=49.8
  Grade 1: Control group N=4758, Mean percentile=49.9
  Grade 2: Control group N=4481, Mean percentile=49.9
  Grade 3: Control group N=4289, Mean percentile=49.9

In [85]:
# Determine entry grade 
def get_entry_grade(row):
    """
    Determine the grade when student first entered STAR program.
    Based on initial assignment (fyclasstype) and when they actually have data.
    """
    # First check: which grade has class type data AND test scores?
    for grade in ['0', '1', '2', '3']:
        class_col = f'g{grade}classtype'
        test_col = f'g{grade}treadss'
        
        # Check if this student has data for this grade
        if class_col in row and pd.notna(row[class_col]):
            if test_col in row and pd.notna(row[test_col]):
                return grade
    return np.nan

df['entry_grade'] = df.apply(get_entry_grade, axis=1)

print(f"Entry grade distribution:")
entry_counts = df['entry_grade'].value_counts().sort_index()
for grade, count in entry_counts.items():
    grade_name = 'Kindergarten' if grade == '0' else f'Grade {grade}'
    print(f"  {grade_name}: {count} ({count/len(df)*100:.1f}%)")

Entry grade distribution:
  Kindergarten: 5789 (49.9%)
  Grade 1: 2385 (20.6%)
  Grade 2: 1346 (11.6%)
  Grade 3: 1140 (9.8%)

## Descriptive Statistics

In [86]:
import numpy as np
import scipy.stats as stats

# ==========================================
# Calculate and Display Statistics for Table I
# ==========================================

# Define cohorts with their descriptive titles
cohorts = {
    '0': {'title': 'A. Students who entered STAR in kindergarten', 'desc': 'kindergarten'},
    '1': {'title': 'B. Students who entered STAR in first grade',  'desc': 'first grade'},
    '2': {'title': 'C. Students who entered STAR in second grade', 'desc': 'second grade'},
    '3': {'title': 'D. Students who entered STAR in third grade',  'desc': 'third grade'}
}

# Configuration for variables to analyze: 
# (internal_key, dynamic_column_pattern, display_template, string_format)
variables = [
    ('free_lunch', 'free_lunch_{g}', '1. Free lunch', '{:.2f}'),
    ('white_asian', 'white_asian',   '2. White/Asian', '{:.2f}'),
    ('age', 'age_1985',              '3. Age in 1985', '{:.2f}'),
    ('class_size', 'g{g}classsize',  '5. Class size in {desc}', '{:.1f}'),
    ('percentile', 'percentile_{g}', '6. Percentile score in {desc}', '{:.1f}')
]

for grade_id, cohort_info in cohorts.items():
    print(f"\n{cohort_info['title']}")
    print("-" * 75)
    
    # Isolate data for the current entry grade
    cohort_data = df[df['entry_grade'] == grade_id]
    
    if cohort_data.empty:
        print("No data available\n")
        continue

    # Partition data into the three experimental groups
    groups = {
        'Small': cohort_data[cohort_data['initial_small'] == 1],
        'Regular': cohort_data[cohort_data['initial_regular'] == 1],
        'Regular/Aide': cohort_data[cohort_data['initial_ra'] == 1]
    }

    # Print Table Header
    print(f"{'Variable':<35} {'Small':<12} {'Regular':<12} {'Regular/Aide':<14} {'Joint P-Value':<15}")
    print("-" * 75)

    for var_key, col_pattern, display_template, format_str in variables:
        # Resolve dynamic column names and display text for the specific grade
        col_name = col_pattern.format(g=grade_id)
        display_name = display_template.format(desc=cohort_info['desc'])
        
        means = []
        anova_data = []

        # Calculate means and collect valid data arrays for ANOVA
        for group_name in ['Small', 'Regular', 'Regular/Aide']:
            group_df = groups[group_name]
            
            if col_name in group_df.columns:
                valid_data = group_df[col_name].dropna()
                
                if not valid_data.empty:
                    means.append(format_str.format(valid_data.mean()))
                    anova_data.append(valid_data)
                else:
                    means.append("NA")
            else:
                means.append("NA")

        # Calculate Joint P-Value (ANOVA) across the groups
        # Note: Class size is mechanically determined by assignment, so ANOVA is omitted
        p_value_str = "NA"
        if var_key != 'class_size' and len(anova_data) >= 2:
            f_stat, p_val = stats.f_oneway(*anova_data)
            
            if not np.isnan(p_val):
                # Format p-value to match standard paper conventions (e.g., .00 for p < 0.01)
                p_value_str = ".00" if p_val < 0.01 else f"{p_val:.2f}"

        # Print the formatted row
        if len(means) == 3:
            print(f"{display_name:<35} {means[0]:<12} {means[1]:<12} {means[2]:<14} {p_value_str:<15}")
        else:
            print(f"{display_name:<35} {'NA':<12} {'NA':<12} {'NA':<14} {'NA':<15}")

    # Print total observations (N) row at the bottom of each cohort block
    n_obs = [str(len(groups[g])) for g in ['Small', 'Regular', 'Regular/Aide']]
    print(f"{'N observations':<35} {n_obs[0]:<12} {n_obs[1]:<12} {n_obs[2]:<14}")

A. Students who entered STAR in kindergarten
---------------------------------------------------------------------------
Variable                            Small        Regular      Regular/Aide   Joint P-Value
---------------------------------------------------------------------------
1. Free lunch                       0.47         0.47         0.50           0.19
2. White/Asian                      0.68         0.68         0.67           0.39
3. Age in 1985                      4.96         4.95         4.95           0.82
5. Class size in kindergarten       15.1         22.3         22.7           NA
6. Percentile score in kindergarten 55.2         49.8         49.8           .00
N observations                      1739         2006         2044

B. Students who entered STAR in first grade
---------------------------------------------------------------------------
Variable                            Small        Regular      Regular/Aide   Joint P-Value
---------------------------------------------------------------------------
1. Free lunch                       0.55         0.58         0.56           0.49
2. White/Asian                      0.61         0.56         0.64           .00
3. Age in 1985                      5.22         5.30         5.31           0.04
5. Class size in first grade        15.9         22.6         23.1           NA
6. Percentile score in first grade  50.5         43.5         48.3           .00
N observations                      437          1041         907

C. Students who entered STAR in second grade
---------------------------------------------------------------------------
Variable                            Small        Regular      Regular/Aide   Joint P-Value
---------------------------------------------------------------------------
1. Free lunch                       0.63         0.60         0.62           0.65
2. White/Asian                      0.52         0.56         0.44           .00
3. Age in 1985                      5.47         5.48         5.50           0.82
5. Class size in second grade       15.4         23.4         23.4           NA
6. Percentile score in second grade 47.2         43.8         41.4           0.02
N observations                      269          533          544

D. Students who entered STAR in third grade
---------------------------------------------------------------------------
Variable                            Small        Regular      Regular/Aide   Joint P-Value
---------------------------------------------------------------------------
1. Free lunch                       0.59         0.59         0.63           0.40
2. White/Asian                      0.67         0.56         0.54           .00
3. Age in 1985                      5.42         5.35         5.46           0.10
5. Class size in third grade        16.0         24.0         24.2           NA
6. Percentile score in third grade  48.3         46.2         42.2           0.01
N observations                      306          420          414

## Regression Analysis Setup

In [87]:
import pandas as pd
import numpy as np

# ==========================================
# Create Long Format Data for Regression Analysis
# ==========================================

long_data = []

# Convert DataFrame to a list of dictionaries for much faster iteration
records = df.to_dict('records')

for idx, row in enumerate(records):
    for grade in ['0', '1', '2', '3']:
        percentile_col = f'percentile_{grade}'
        
        # Check if the student has a valid test score for this grade
        if pd.notna(row.get(percentile_col)):
            class_type_val = row.get(f'g{grade}classtype')
            
            # Append the observation
            long_data.append({
                'student_id': idx,
                'grade': int(grade),
                'percentile': row[percentile_col],
                
                # Actual class assignment indicators
                'small_class': int(class_type_val == 1) if pd.notna(class_type_val) else 0,
                'reg_aide_class': int(class_type_val == 3) if pd.notna(class_type_val) else 0,
                
                # Initial assignment (instrumental variables)
                'initial_small': int(row.get('initial_small', 0)),
                'initial_ra': int(row.get('initial_ra', 0)),
                
                # Student characteristics
                'white_asian': int(row.get('white_asian', 0)),
                'girl': int(row.get('girl', 0)),
                'free_lunch': int(row.get(f'free_lunch_{grade}', 0)),
                
                # School fixed effects
                'school_id': str(row.get(f'g{grade}schid', '')),
                
                # Teacher characteristics
                'teacher_white': row.get(f'WhiteTeacher{grade}', 0),
                'teacher_exp': float(row.get(f'g{grade}tyears', 0)) if pd.notna(row.get(f'g{grade}tyears')) else np.nan,
                'teacher_degree_raw': row.get(f'g{grade}thighdegree', ''),
                
                # Class size
                'class_size': float(row.get(f'g{grade}classsize', np.nan))
            })

# Convert the compiled list of observations into a DataFrame
long_df = pd.DataFrame(long_data)

# ==========================================
# Clean Teacher Degree Variable
# ==========================================

# Map raw degree strings to a binary indicator (1 = Master's or higher, 0 = Bachelor's/Specialist)
degree_map = {
    'bachelors': 0,
    'specialist': 0,
    'masters': 1,
    'masters +': 1,
    'doctoral': 1
}

# Apply lowercase transformation and map the values securely
long_df['teacher_masters'] = long_df['teacher_degree_raw'].astype(str).str.lower().map(degree_map)

# Drop the temporary raw degree column
long_df = long_df.drop(columns=['teacher_degree_raw'])

# Display the first few rows to verify the transformation
long_df.head()

,student_id,grade,percentile,small_class,reg_aide_class,initial_small,initial_ra,white_asian,girl,free_lunch,school_id,teacher_white,teacher_exp,class_size,teacher_masters
0,0,3,0.000000,0,0,0,0,0,0,1,169280.0,1.0,30.0,25.0,0.0
1,1,3,0.046631,0,1,0,1,0,0,1,193422.0,1.0,17.0,25.0,1.0
2,2,3,0.279785,0,1,0,1,1,0,0,264945.0,1.0,16.0,28.0,1.0
3,3,1,6.809584,0,0,0,0,0,0,1,244780.0,1.0,2.0,25.0,0.0
4,3,2,4.909618,0,0,0,0,0,0,1,244780.0,1.0,1.0,21.0,0.0

## OLS Regression Analysis

In [88]:
import pandas as pd
import numpy as np
import statsmodels.api as sm

# ==========================================
# Regression Core Function
# ==========================================

def run_regression_extended(data, grade, model_type, controls_level):
    """
    Prepares the design matrix and runs OLS or Reduced Form regressions
    with varying levels of controls and school fixed effects.
    """
    # 1. Filter data and define target variables
    df_g = data[data['grade'] == grade].copy()
    
    if model_type == 'ols':
        treatment_vars = ['small_class', 'reg_aide_class']
    else:  # reduced_form
        treatment_vars = ['initial_small', 'initial_ra']
        
    student_controls = ['white_asian', 'girl', 'free_lunch']
    teacher_controls = ['teacher_white', 'teacher_exp', 'teacher_masters']
    
    # 2. Determine control variables based on specification level
    controls = []
    use_school_fe = False
    
    if controls_level >= 2:
        use_school_fe = True
    if controls_level >= 3:
        controls.extend(student_controls)
    if controls_level >= 4:
        controls.extend(teacher_controls)
        
    # 3. Build dataset for regression
    req_cols = ['percentile'] + treatment_vars + controls
    if use_school_fe:
        req_cols.append('school_id')
        
    # Keep only available columns and drop missing observations
    req_cols = [c for c in req_cols if c in df_g.columns]
    df_reg = df_g[req_cols].dropna().copy()
    
    if len(df_reg) < 10:
        return None

    # 4. Construct Design Matrix (X) and Outcome (y)
    y = df_reg['percentile'].astype(float)
    X = df_reg[treatment_vars + controls].astype(float)
    X = sm.add_constant(X)
    
    if use_school_fe:
        # Generate school fixed effects, dropping the first to avoid perfect multicollinearity
        school_dummies = pd.get_dummies(df_reg['school_id'].astype(str), prefix='sch', drop_first=True, dtype=float)
        X = pd.concat([X, school_dummies], axis=1)

    # 5. Fit Model with Fallback Standard Errors
    try:
        # Primary: Clustered standard errors at the school level
        model = sm.OLS(y, X).fit(cov_type='cluster', cov_kwds={'groups': df_reg['school_id']})
    except Exception:
        try:
            # Fallback 1: Heteroskedasticity-robust standard errors (HC1)
            model = sm.OLS(y, X).fit(cov_type='HC1')
        except Exception:
            # Fallback 2: Standard Homoskedastic OLS
            model = sm.OLS(y, X).fit()

    # 6. Return compiled results
    return {
        'params': model.params.to_dict(),
        'bse': model.bse.to_dict(),
        'r2': model.rsquared,
        'n_obs': len(df_reg),
        'school_fe': use_school_fe,
        'controls_level': controls_level,
        'model_type': model_type
    }

# ==========================================
# Formatting Helpers
# ==========================================

def format_coef_se(coef, se, add_stars=False):
    """Formats coefficient and standard error, optionally adding significance stars."""
    if coef is None or se is None or pd.isna(coef):
        return "—"
    
    stars = ""
    if add_stars and se > 0:
        t_stat = abs(coef / se)
        if t_stat > 2.576:   stars = "***" # p < 0.01
        elif t_stat > 1.960: stars = "**"  # p < 0.05
        elif t_stat > 1.645: stars = "*"   # p < 0.10
            
    # Format with 2 decimal places (3 if SE is very small)
    decimals = 3 if abs(se) < 0.01 else 2
    return f"{coef:.{decimals}f}{stars} ({se:.{decimals}f})"

# ==========================================
# Execute Regressions Across Grades
# ==========================================

results = {}
grades = [0, 1, 2, 3]
grade_names = ['Kindergarten', 'Grade 1', 'Grade 2', 'Grade 3']

for grade_num, grade_name in zip(grades, grade_names):
    grade_results = {}
    
    for col in [1, 2, 3, 4]:
        # Run OLS (Actual assignment)
        grade_results[f'ols_{col}'] = run_regression_extended(long_df, grade_num, 'ols', col)
        # Run Reduced Form (Initial assignment)
        grade_results[f'rf_{col}'] = run_regression_extended(long_df, grade_num, 'reduced_form', col)
        
    results[grade_name] = grade_results

# ==========================================
# Generate Summary Output
# ==========================================

print("\n" + "="*100)
print("SUMMARY OF MAIN RESULTS - Small Class Effects")
print("="*100)

summary_headers = ["Grade", "OLS (3)", "OLS (4)", "Reduced Form (7)", "Reduced Form (8)"]
print(" | ".join([h.ljust(18) for h in summary_headers]))
print("-" * 100)

for grade_name in grade_names:
    grade_res = results[grade_name]
    row_vals = [grade_name]
    
    for spec, var_name in [('ols_3', 'small_class'), ('ols_4', 'small_class'), 
                           ('rf_3', 'initial_small'), ('rf_4', 'initial_small')]:
        
        res = grade_res.get(spec)
        if res:
            c = res['params'].get(var_name)
            s = res['bse'].get(var_name)
            row_vals.append(format_coef_se(c, s, add_stars=True))
        else:
            row_vals.append("—")
            
    print(" | ".join([str(x).ljust(18) for x in row_vals]))
    
print("\nNote: *** p<0.01, ** p<0.05, * p<0.10")

====================================================================================================
SUMMARY OF MAIN RESULTS - Small Class Effects
====================================================================================================
Grade              | OLS (3)            | OLS (4)            | Reduced Form (7)   | Reduced Form (8)
----------------------------------------------------------------------------------------------------
Kindergarten       | 5.79*** (1.45)     | 5.66*** (1.42)     | 5.79*** (1.45)     | 5.66*** (1.42)
Grade 1            | 8.63*** (1.43)     | 8.28*** (1.45)     | 7.32*** (1.32)     | 7.10*** (1.31)
Grade 2            | 6.26*** (1.51)     | 6.28*** (1.51)     | 5.96*** (1.31)     | 5.91*** (1.31)
Grade 3            | 5.50*** (1.32)     | 5.37*** (1.34)     | 5.86*** (1.14)     | 5.79*** (1.19)

Note: *** p<0.01, ** p<0.05, * p<0.10

## TSLS with covariates

In [89]:
#!pip install linearmodels

In [ ]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
from linearmodels.iv import IV2SLS

# ==========================================
# Data Preparation
# ==========================================

# Create initial_regular variable (Regular without aide)
long_df['initial_regular'] = 1 - long_df['initial_small'] - long_df['initial_ra']

# Ensure logical consistency (clip any negative values to 0)
if (long_df['initial_regular'] < 0).any():
    long_df['initial_regular'] = long_df['initial_regular'].clip(lower=0)

# ==========================================
# 2SLS Regression Core Function
# ==========================================

def run_2sls_regression_fixed(data, grade, include_controls=True, include_school_fe=True):
    """
    Runs a 2SLS regression for a specific grade using the Matrix API.
    Returns correct 2SLS standard errors via the linearmodels package.
    """
    df_g = data[data['grade'] == grade].copy()
    
    # Define required variables
    # Note: Assuming 'small_class' is the endogenous treatment variable
    req_vars = ['percentile', 'small_class', 'initial_small', 'initial_regular']
    df_g = df_g.dropna(subset=req_vars)
    
    if len(df_g) < 10:
        return None

    # --------------------------------------------------------
    # 1. Define Exogenous Controls & Handle Missing Values
    # --------------------------------------------------------
    exog_cols = []
    
    if include_controls:
        # Impute missing continuous variables with median, binary/categorical with mean
        if 'teacher_exp' in df_g.columns:
            df_g['teacher_exp'] = df_g['teacher_exp'].fillna(df_g['teacher_exp'].median())
            
        student_controls = ['white_asian', 'girl', 'free_lunch']
        teacher_controls = ['teacher_white', 'teacher_exp', 'teacher_masters']
        
        for col in student_controls + teacher_controls:
            if col in df_g.columns:
                #df_g[col] = df_g[col].fillna(df_g[col].mean())
                df_g[col] = df_g[col].fillna(df_g[col].mode()[0])
                exog_cols.append(col)

    # Add School Fixed Effects
    if include_school_fe:
        # Create dummies and drop the first to avoid perfect multicollinearity (dummy trap)
        school_dummies = pd.get_dummies(df_g['school_id'].astype(str), prefix='sch', drop_first=True, dtype=float)
        df_g = pd.concat([df_g, school_dummies], axis=1)
        exog_cols.extend(school_dummies.columns)

    # --------------------------------------------------------
    # 2. Construct Regression Matrices
    # --------------------------------------------------------
    y = df_g['percentile']
    D = df_g[['small_class']] # Endogenous variable
    Z = df_g[['initial_small', 'initial_regular']] # Instruments
    
    # Exogenous matrix (Controls + FE + Constant)
    if exog_cols:
        X_exog = sm.add_constant(df_g[exog_cols].astype(float))
    else:
        # If no controls, X_exog is just a column of ones (the constant)
        X_exog = sm.add_constant(pd.DataFrame(np.ones(len(df_g)), index=df_g.index, columns=['const']))

    # --------------------------------------------------------
    # 3. First Stage (Extract F-Statistic)
    # --------------------------------------------------------
    # Regress endogenous variable on instruments + exogenous controls
    first_stage_exog = pd.concat([Z, X_exog], axis=1)
    fs_model = sm.OLS(D, first_stage_exog).fit()
    fs_f_stat = fs_model.fvalue

    # --------------------------------------------------------
    # 4. Standard OLS (For Baseline Comparison)
    # --------------------------------------------------------
    ols_exog = pd.concat([D, X_exog], axis=1)
    ols_model = sm.OLS(y, ols_exog).fit()
    
    # --------------------------------------------------------
    # 5. IV / 2SLS Estimation (linearmodels)
    # --------------------------------------------------------
    # We use linearmodels instead of manual 2-stage OLS to ensure standard errors
    # are mathematically adjusted for the first-stage estimation variance.
    try:
        iv_model = IV2SLS(dependent=y, exog=X_exog, endog=D, instruments=Z).fit(cov_type='robust')
    except Exception as e:
        print(f"  Grade {grade} IV2SLS Error: {e}")
        return None

    # Compile and return results
    return {
        'n_obs': len(df_g),
        'fs_f_stat': fs_f_stat,
        'ols_coef': ols_model.params['small_class'],
        'ols_se': ols_model.bse['small_class'],
        'iv_coef': iv_model.params['small_class'],
        'iv_se': iv_model.std_errors['small_class']
    }

# ==========================================
# Execute Regressions and Format Table VII
# ==========================================

grades = [0, 1, 2, 3]
grade_names = ['Kindergarten', 'Grade 1', 'Grade 2', 'Grade 3']
table_rows = [["Grade", "OLS", "2SLS", "Sample Size", "First Stage F"]]

for grade_num, grade_name in zip(grades, grade_names):
    res = run_2sls_regression_fixed(long_df, grade_num, include_controls=True, include_school_fe=True)
    
    if res:
        ols_str = f"{res['ols_coef']:.2f} ({res['ols_se']:.2f})"
        iv_str  = f"{res['iv_coef']:.2f} ({res['iv_se']:.2f})"
        n_obs   = f"{res['n_obs']:,}"
        fs_f    = f"{res['fs_f_stat']:.1f}"
        
        table_rows.append([grade_name, ols_str, iv_str, n_obs, fs_f])
    else:
        table_rows.append([grade_name, "—", "—", "—", "—"])

# Print Final Formatted Table
print("\n" + "="*100)
print("TABLE VII - OLS AND 2SLS ESTIMATES OF EFFECT OF SMALL CLASS ON ACHIEVEMENT")
print("DEPENDENT VARIABLE: AVERAGE PERCENTILE SCORE ON SAT")
print("="*100)

for row in table_rows:
    print(f"{row[0]:<15} {row[1]:<20} {row[2]:<20} {row[3]:<15} {row[4]:<15}")
print("-" * 90)
print("Note: All models include school fixed effects, student race, gender, free lunch status,")
print("teacher race, experience, and education. Standard errors in parentheses.")

====================================================================================================
TABLE VII - OLS AND 2SLS ESTIMATES OF EFFECT OF SMALL CLASS ON ACHIEVEMENT
DEPENDENT VARIABLE: AVERAGE PERCENTILE SCORE ON SAT
====================================================================================================
Grade           OLS                  2SLS                 Sample Size     First Stage F
Kindergarten    5.54 (0.71)          5.54 (0.72)          5,902           43216781206059756310818193408.0
Grade 1         7.38 (0.68)          7.10 (0.79)          6,635           267.4
Grade 2         5.53 (0.70)          6.37 (0.85)          6,360           188.0
Grade 3         5.85 (0.72)          7.30 (0.94)          6,355           127.8
------------------------------------------------------------------------------------------
Note: All models include school fixed effects, student race, gender, free lunch status,
teacher race, experience, and education. Standard errors in parentheses.

## TSLS without covariates

In [91]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
from linearmodels.iv import IV2SLS

# ==========================================
# Data Preparation
# ==========================================

# Ensure 'initial_regular' exists and is strictly non-negative
if 'initial_regular' not in long_df.columns:
    long_df['initial_regular'] = 1 - long_df['initial_small'] - long_df['initial_ra']
    long_df['initial_regular'] = long_df['initial_regular'].clip(lower=0)

# ==========================================
# Unconditional IV Regression Function
# ==========================================

def run_iv_no_covariates(data, grade):
    """
    Runs a baseline IV / 2SLS regression for a specific grade.
    This specification contains NO covariates and NO school fixed effects.
    Endogenous regressor: small_class
    Instrument: initial_small
    """
    # 1. Filter data and isolate required variables
    df_g = data[data['grade'] == grade].copy()
    req_vars = ['percentile', 'small_class', 'initial_small']
    df_g = df_g.dropna(subset=req_vars)
    
    if len(df_g) < 10:
        return None

    # 2. Define regression matrices
    y = df_g['percentile']
    D = df_g[['small_class']]     # Endogenous variable
    Z = df_g[['initial_small']]   # Instrument
    
    # Since there are no covariates, our exogenous matrix is just a constant (intercept)
    X_exog = sm.add_constant(pd.DataFrame(np.ones(len(df_g)), index=df_g.index, columns=['const']))

    # 3. First Stage (Extract F-Statistic for instrument strength)
    first_stage_exog = pd.concat([Z, X_exog], axis=1)
    fs_model = sm.OLS(D, first_stage_exog).fit()
    fs_f_stat = fs_model.fvalue

    # 4. Standard OLS (For baseline comparison, ignoring endogeneity)
    ols_exog = pd.concat([D, X_exog], axis=1)
    ols_model = sm.OLS(y, ols_exog).fit()

    # 5. IV / 2SLS Estimation (linearmodels)
    # This automatically computes the correctly adjusted second-stage standard errors.
    try:
        iv_model = IV2SLS(dependent=y, exog=X_exog, endog=D, instruments=Z).fit(cov_type='robust')
    except Exception as e:
        print(f"  Grade {grade} IV2SLS Error: {e}")
        return None

    # Compile and return results
    return {
        'n_obs': len(df_g),
        'fs_f_stat': fs_f_stat,
        'ols_coef': ols_model.params['small_class'],
        'ols_se': ols_model.bse['small_class'],
        'iv_coef': iv_model.params['small_class'],
        'iv_se': iv_model.std_errors['small_class']
    }

# ==========================================
# Execute Regressions Across Grades
# ==========================================

grades = [0, 1, 2, 3]
grade_names = ['Kindergarten', 'Grade 1', 'Grade 2', 'Grade 3']
table_rows = [["Grade", "OLS", "IV", "Sample Size", "First Stage F"]]

for grade_num, grade_name in zip(grades, grade_names):
    res = run_iv_no_covariates(long_df, grade_num)
    
    if res:
        ols_str = f"{res['ols_coef']:.2f} ({res['ols_se']:.2f})"
        iv_str  = f"{res['iv_coef']:.2f} ({res['iv_se']:.2f})"
        n_obs   = f"{res['n_obs']:,}"
        fs_f    = f"{res['fs_f_stat']:.1f}"
        
        table_rows.append([grade_name, ols_str, iv_str, n_obs, fs_f])
    else:
        table_rows.append([grade_name, "—", "—", "—", "—"])

# ==========================================
# Generate Formatted Output Table
# ==========================================

print("\n\n" + "="*100)
print("IV ESTIMATES OF EFFECT OF SMALL CLASS ON ACHIEVEMENT (NO COVARIATES)")
print("DEPENDENT VARIABLE: AVERAGE PERCENTILE SCORE ON SAT")
print("="*100)

for row in table_rows:
    print(f"{row[0]:<15} {row[1]:<20} {row[2]:<20} {row[3]:<15} {row[4]:<15}")
print("-" * 90)

print("Note: No covariates and no school fixed effects are included.")
print("Robust standard errors are shown in parentheses.")

====================================================================================================
IV ESTIMATES OF EFFECT OF SMALL CLASS ON ACHIEVEMENT (NO COVARIATES)
DEPENDENT VARIABLE: AVERAGE PERCENTILE SCORE ON SAT
====================================================================================================
Grade           OLS                  IV                   Sample Size     First Stage F
Kindergarten    5.06 (0.83)          5.06 (0.83)          5,902           631001830160937933183781676515328.0
Grade 1         7.67 (0.79)          8.10 (0.91)          6,635           20307.7
Grade 2         5.64 (0.79)          6.92 (0.96)          6,360           13657.7
Grade 3         6.13 (0.78)          7.90 (1.01)          6,355           9128.3
------------------------------------------------------------------------------------------
Note: No covariates and no school fixed effects are included.
Robust standard errors are shown in parentheses.

## DDML Analysis

In [92]:
#!pip install DoubleML
#!pip install econml

In [93]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from doubleml import DoubleMLData, DoubleMLPLR
import pickle

# Display configuration
pd.set_option('display.max_columns', None)

# ==========================================
# DDML ANALYSIS BY GRADE
# ==========================================
print("="*80)
print("DDML ESTIMATION OF SMALL CLASS EFFECTS BY GRADE")
print("="*80)

# Dictionary to store the results
ddml_results_by_grade = {}

grades = [
    (0, 'Kindergarten'), 
    (1, 'Grade 1'), 
    (2, 'Grade 2'), 
    (3, 'Grade 3')
]

for grade_num, grade_name in grades:
    print(f"\n{grade_name}:")
    print("-" * 40)
    
    # 1. Filter data by grade
    grade_data = long_df[long_df['grade'] == grade_num].copy()
    
    # 2. Drop missing values for required columns
    req_cols = [
        'percentile', 'small_class', 'white_asian', 'girl', 
        'free_lunch', 'teacher_exp', 'teacher_masters', 'teacher_white'
    ]
    grade_data = grade_data.dropna(subset=req_cols)
    
    print(f"  Observations: {len(grade_data)}")
    print(f"  Unique students: {grade_data['student_id'].nunique()}")
    print(f"  Small class share: {grade_data['small_class'].mean():.1%}")
    
    # 3. Create DoubleMLData object for current grade
    try:
        dml_grade = DoubleMLData(
            grade_data,
            y_col='percentile',
            d_cols='small_class',
            x_cols=[c for c in req_cols if c not in ['percentile', 'small_class']]
        )
        
        # 4. Initialize and fit DDML model (Partially Linear Regression)
        ml_g = RandomForestRegressor(n_estimators=100, max_depth=5, random_state=42)
        ml_m = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=42)
        
        dml_plr_grade = DoubleMLPLR(dml_grade, ml_g, ml_m, n_folds=5)
        dml_plr_grade.fit()
        
        # 5. Extract and store results safely
        ate = dml_plr_grade.coef[0]
        se = dml_plr_grade.se[0]
        confint_df = dml_plr_grade.confint()
        
        ci_lower = confint_df.iloc[0, 0] if not confint_df.empty else None
        ci_upper = confint_df.iloc[0, 1] if not confint_df.empty else None
        
        ddml_results_by_grade[grade_name] = {
            'model': dml_plr_grade,
            'ate': ate,
            'se': se,
            'ci_lower': ci_lower,
            'ci_upper': ci_upper,
            'n_obs': len(grade_data)
        }
        
        print(f"  ATE (DDML): {ate:.3f} (SE: {se:.3f})")
        if ci_lower is not None:
            print(f"  95% CI: [{ci_lower:.3f}, {ci_upper:.3f}]")
        else:
            print("  95% CI: [Not available]")
            
    except Exception as e:
        print(f"  Error fitting DDML for {grade_name}: {e}")
        ddml_results_by_grade[grade_name] = None


# ==========================================
# FINAL SUMMARY TABLE
# ==========================================
print("\n" + "="*80)
print("SUMMARY TABLE: DDML ESTIMATES FOR SMALL CLASS EFFECT")
print("="*80)

print(f"{'Grade':<15} {'N (DDML)':<10} {'DDML ATE':<12} {'DDML SE':<10} {'95% CI (DDML)':<25}")
print("-" * 75)

for _, grade_name in grades:
    if grade_name in ddml_results_by_grade and ddml_results_by_grade[grade_name] is not None:
        res = ddml_results_by_grade[grade_name]
        
        ci_str = f"[{res['ci_lower']:.3f}, {res['ci_upper']:.3f}]" if res['ci_lower'] is not None else "[N/A]"
        
        print(f"{grade_name:<15} {res['n_obs']:<10} {res['ate']:<12.3f} "
              f"{res['se']:<10.3f} {ci_str:<25}")
    else:
        print(f"{grade_name:<15} {'-':<10} {'-':<12} {'-':<10} {'-':<25}")

================================================================================
DDML ESTIMATION OF SMALL CLASS EFFECTS BY GRADE
================================================================================

Kindergarten:
----------------------------------------
  Observations: 5859
  Unique students: 5859
  Small class share: 30.2%

  ATE (DDML): 5.214 (SE: 0.819)
  95% CI: [3.608, 6.819]

Grade 1:
----------------------------------------
  Observations: 6622
  Unique students: 6622
  Small class share: 28.1%
  ATE (DDML): 5.809 (SE: 0.749)
  95% CI: [4.341, 7.278]

Grade 2:
----------------------------------------
  Observations: 6273
  Unique students: 6273
  Small class share: 29.7%
  ATE (DDML): 4.624 (SE: 0.753)
  95% CI: [3.147, 6.100]

Grade 3:
----------------------------------------
  Observations: 6290
  Unique students: 6290
  Small class share: 32.6%
  ATE (DDML): 4.918 (SE: 0.771)
  95% CI: [3.408, 6.428]

================================================================================
SUMMARY TABLE: DDML ESTIMATES FOR SMALL CLASS EFFECT
================================================================================
Grade           N (DDML)   DDML ATE     DDML SE    95% CI (DDML)
---------------------------------------------------------------------------
Kindergarten    5859       5.214        0.819      [3.608, 6.819]
Grade 1         6622       5.809        0.749      [4.341, 7.278]
Grade 2         6273       4.624        0.753      [3.147, 6.100]
Grade 3         6290       4.918        0.771      [3.408, 6.428]

## RESET Test

In [94]:
import pandas as pd
import statsmodels.formula.api as smf
from statsmodels.stats.outliers_influence import reset_ramsey
from IPython.display import display

print("="*80)
print("RAMSEY RESET TEST FOR RICH COVARIATES")
print("="*80)

# Initialize a list to store the results
reset_results = []

# Map grade numbers to their descriptive names
grades = {'0': 'Kindergarten', '1': 'Grade 1', '2': 'Grade 2', '3': 'Grade 3'}

for g_num, g_name in grades.items():
    # Define grade-specific variable names exactly as they are in your notebook
    free_lunch = f'free_lunch_{g_num}'
    t_race = f'WhiteTeacher{g_num}'
    t_exp = f'g{g_num}tyears'
    t_md = f'g{g_num}md'
    sch_id = f'g{g_num}schid'
    
    # List of all variables needed for the projection
    cols = ['initial_small', 'white_asian', 'girl', free_lunch, t_race, t_exp, t_md, sch_id]
    
    # Filter out rows with missing data for these specific variables
    df_g = df.dropna(subset=cols).copy()
    
    # Ensure variables are strictly numeric (except school ID which will be treated as categorical)
    for col in cols:
        if col != sch_id:
            df_g[col] = pd.to_numeric(df_g[col], errors='coerce')
    
    df_g = df_g.dropna(subset=cols)
    
    # Formulate the linear projection: Instrument ~ Covariates + School Fixed Effects
    formula = f'initial_small ~ white_asian + girl + {free_lunch} + {t_race} + {t_exp} + {t_md} + C({sch_id})'
    
    try:
        # Fit the first-stage OLS model (Linear Projection)
        model = smf.ols(formula, data=df_g).fit()
        
        # Run the Ramsey RESET test (using squared and cubed fitted values)
        reset_test = reset_ramsey(model, degree=3)
        
        # Determine whether the Rich Covariates condition is rejected (alpha = 0.05)
        reject_null = "Yes" if reset_test.pvalue < 0.05 else "No"
        
        # Append the results
        reset_results.append({
            'Specification / Cohort': g_name,
            'Sample Size (N)': len(df_g),
            'RESET F-statistic': round(reset_test.statistic, 3),
            'p-value': round(reset_test.pvalue, 4),
            'Reject H0 (Rich Covariates)?': reject_null
        })
        
    except Exception as e:
        print(f"Error processing {g_name}: {e}")

# Convert the results to a DataFrame for clean, tabular visualization
table_3_replication = pd.DataFrame(reset_results)

# Display the final table
display(table_3_replication)

================================================================================
RAMSEY RESET TEST FOR RICH COVARIATES
================================================================================

,Specification / Cohort,Sample Size (N),RESET F-statistic,p-value,Reject H0 (Rich Covariates)?
0,Kindergarten,6282,33.671,0.0000,Yes
1,Grade 1,6810,18.538,0.0000,Yes
2,Grade 2,6739,6.255,0.0019,Yes
3,Grade 3,6736,52.171,0.0000,Yes

## DDML LATE

In [ ]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
import doubleml as dml

def calculate_late_ddml(data, grade):
    df_g = data[data['grade'] == grade].copy()
    
    # Define covariates (matching your previous lists)
    covariates = [
        'white_asian', 'girl', 'free_lunch', 
        'teacher_white', 'teacher_exp', 'teacher_masters'
    ]
    # Add school dummies to covariates
    school_dummies = pd.get_dummies(df_g['school_id'].astype(str), prefix='sch', drop_first=True)
    df_g = pd.concat([df_g, school_dummies], axis=1)
    x_cols = covariates + list(school_dummies.columns)
    
    # Drop NAs
    df_g = df_g.dropna(subset=['percentile', 'small_class', 'initial_small'] + covariates)
    
    # Setup DoubleML Data Object
    # Y = Outcome, D = Treatment (Binary), Z = Instrument (Binary)
    dml_data = dml.DoubleMLData(df_g, 
                                y_col='percentile', 
                                d_cols='small_class', 
                                z_cols='initial_small', 
                                x_cols=x_cols)
    
    # Define Machine Learning algorithms (Random Forests)
    # ml_g: Predicts Y given X and Z
    ml_g = RandomForestRegressor(n_estimators=100, max_depth=5, random_state=42)
    # ml_m: Predicts Z given X (Propensity score of instrument)
    ml_m = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=42)
    # ml_r: Predicts D given X and Z (Treatment probability)
    ml_r = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=42)
    
    # Set numpy random seed for reproducible sample splitting in DoubleML
    np.random.seed(42)
    
    # Initialize Interactive IV Model (IIVM) for LATE estimation (removed random_state)
    dml_iivm = dml.DoubleMLIIVM(dml_data, ml_g, ml_m, ml_r, n_folds=5)
    
    # Fit the model
    dml_iivm.fit()
    
    coef = dml_iivm.coef[0]
    se = dml_iivm.se[0]
    
    print(f"Grade {grade} - DDML LATE: {coef:.3f} ({se:.3f})")
    return coef, se

# Run for all grades:
for g in [0, 1, 2, 3]:
    calculate_late_ddml(long_df, g)

Grade 0 - DDML LATE: 4.989 (0.729)
Grade 1 - DDML LATE: 7.282 (0.795)
Grade 2 - DDML LATE: 6.641 (0.855)
Grade 3 - DDML LATE: 6.722 (0.933)

## IPSW LATE

In [96]:
import statsmodels.api as sm

def calculate_late_ipsw(data, grade):
    df_g = data[data['grade'] == grade].copy()
    
    covariates = [
        'white_asian', 'girl', 'free_lunch', 
        'teacher_white', 'teacher_exp', 'teacher_masters'
    ]
    school_dummies = pd.get_dummies(df_g['school_id'].astype(str), prefix='sch', drop_first=True)
    df_g = pd.concat([df_g, school_dummies], axis=1)
    x_cols = covariates + list(school_dummies.columns)
    
    df_g = df_g.dropna(subset=['percentile', 'small_class', 'initial_small'] + covariates)
    
    Y = df_g['percentile'].values
    T = df_g['small_class'].values
    Z = df_g['initial_small'].values
    X = sm.add_constant(df_g[x_cols].astype(float))
    
    # 1. Estimate Instrument Propensity Score E[Z|X] using Logit
    logit_model = sm.Logit(Z, X).fit(disp=0)
    p_X = logit_model.predict(X)
    
    # Trim probabilities to avoid division by zero / extreme weights
    p_X = np.clip(p_X, 0.01, 0.99)
    
    # 2. Calculate Normalized Weights (Hajek Estimator)
    w1 = Z / p_X
    w0 = (1 - Z) / (1 - p_X)
    
    w1_norm = w1 / np.sum(w1)
    w0_norm = w0 / np.sum(w0)
    
    # 3. Calculate Numerator (Average Causal Effect of Z on Y)
    itt_Y = np.sum(w1_norm * Y) - np.sum(w0_norm * Y)
    
    # 4. Calculate Denominator (Average Causal Effect of Z on T)
    itt_T = np.sum(w1_norm * T) - np.sum(w0_norm * T)
    
    # 5. IPSW LATE/ACR Estimate
    beta_ipsw = itt_Y / itt_T
    
    print(f"Grade {grade} - IPSW LATE: {beta_ipsw:.3f}")
    
    # Note: Analytical standard errors for IPSW require GMM or bootstrapping.
    return beta_ipsw

# Run for all grades:
for g in [0, 1, 2, 3]:
    calculate_late_ipsw(long_df, g)

Grade 0 - IPSW LATE: 5.529
Grade 1 - IPSW LATE: 7.234
Grade 2 - IPSW LATE: 6.655
Grade 3 - IPSW LATE: 7.459

## IPSW LATE SE

In [ ]:
import numpy as np
import pandas as pd
import statsmodels.api as sm

def compute_ipsw_point_estimate(df_est, x_cols):
    """Core function to calculate the IPSW LATE point estimate."""
    Y = df_est['percentile'].values
    T = df_est['small_class'].values
    Z = df_est['initial_small'].values
    X = sm.add_constant(df_est[x_cols].astype(float))
    
    # Estimate Instrument Propensity Score E[Z|X]
    logit_model = sm.Logit(Z, X).fit(disp=0, method='bfgs') 
    p_X = logit_model.predict(X)
    p_X = np.clip(p_X, 0.01, 0.99) # Trim to prevent extreme weights
    
    # Calculate Hajek Weights
    w1 = Z / p_X
    w0 = (1 - Z) / (1 - p_X)
    w1_norm = w1 / np.sum(w1)
    w0_norm = w0 / np.sum(w0)
    
    # Calculate components and ratio
    itt_Y = np.sum(w1_norm * Y) - np.sum(w0_norm * Y)
    itt_T = np.sum(w1_norm * T) - np.sum(w0_norm * T)

    logit_model = sm.Logit(Z, X).fit(disp=0, method='bfgs', warn_convergence=False)
    
    return itt_Y / itt_T

def calculate_late_ipsw_with_se(data, grade, B=500):
    """Calculates IPSW LATE and its cluster-robust standard error."""
    df_g = data[data['grade'] == grade].copy()
    
    covariates = [
        'white_asian', 'girl', 'free_lunch', 
        'teacher_white', 'teacher_exp', 'teacher_masters'
    ]
    school_dummies = pd.get_dummies(df_g['school_id'].astype(str), prefix='sch', drop_first=True)
    df_g = pd.concat([df_g, school_dummies], axis=1)
    x_cols = covariates + list(school_dummies.columns)
    
    df_g = df_g.dropna(subset=['percentile', 'small_class', 'initial_small', 'school_id'] + covariates)
    
    # 1. Calculate Point Estimate on full sample
    point_est = compute_ipsw_point_estimate(df_g, x_cols)
    
    # 2. Cluster Bootstrap for Standard Error
    clusters = df_g['school_id'].unique()
    n_clusters = len(clusters)
    boot_estimates = []
    
    np.random.seed(42) # Ensure reproducibility
    
    print(f"Grade {grade} - Running {B} bootstrap iterations...")
    for b in range(B):
        # Sample clusters with replacement
        boot_cluster_sample = np.random.choice(clusters, size=n_clusters, replace=True)
        
        # Reconstruct dataframe from sampled clusters
        boot_df_list = [df_g[df_g['school_id'] == cluster] for cluster in boot_cluster_sample]
        boot_df = pd.concat(boot_df_list, axis=0)
        
        try:
            boot_est = compute_ipsw_point_estimate(boot_df, x_cols)
            boot_estimates.append(boot_est)
        except Exception:
            # Logit may fail to converge in some bootstrap samples due to perfect separation
            continue
            
    # Compute Standard Error from the bootstrap distribution
    se_boot = np.std(boot_estimates, ddof=1)
    
    print(f"Grade {grade} - IPSW LATE: {point_est:.3f} ({se_boot:.3f})")
    print(f"Failed bootstrap iterations: {B - len(boot_estimates)}")
    
    return point_est, se_boot

# Run for a specific grade (e.g., Kindergarten)
ipsw_coef, ipsw_se = calculate_late_ipsw_with_se(long_df, grade=0, B=500)

Grade 0 - Running 500 bootstrap iterations...
Grade 0 - IPSW LATE: 5.411 (1.383)
Failed bootstrap iterations: 0